#CTI-110
#M6T1b-Initials
#Marie Hylton
#27 November 2017

def main():
    import turtle
    play=turtle.Screen()
    play.title("My Initials")
    jesse=turtle.Turtle()
    jesse.shape("turtle")
    play.bgcolor("coral")
    jesse.pensize("5")
    #My Initials are: CMH, standing for Cu'Tris Marie Hylton
    #Must change pensize and color

    #program for creating C:
    jesse.color("navy")
    jesse.begin_fill()
    jesse.forward(75)
    jesse.left(90)
    jesse.forward(12)
    jesse.left(90)
    jesse.forward(50)
    jesse.right(90)
    jesse.forward(25)
    jesse.right(90)
    jesse.forward(50)
    jesse.left(90)
    jesse.forward(12)
    jesse.left(90)
    jesse.forward(75)
    jesse.left(90)
    jesse.forward(50)
    jesse.end_fill()
    jesse.penup()

    #program for creating M:
 
    jesse.color("navy")
    jesse.begin_fill()
    jesse.penup()
    jesse.left(90)
    jesse.forward(100)
    jesse.pendown()
    jesse.left(90)
    jesse.forward(50)
    jesse.right(90)
    jesse.forward(25)
    jesse.right(45)
    jesse.forward(20)
    jesse.left(90)
    jesse.forward(20)
    jesse.right(45)
    jesse.forward(25)
    jesse.right(90)
    jesse.forward(50)
    jesse.right(90)
    jesse.forward(25)
    jesse.right(90)
    jesse.forward(36)
    jesse.left(135)
    jesse.forward(20)
    jesse.right(90)
    jesse.forward(20)
    jesse.left(135)
    jesse.forward(36)
    jesse.right(90)
    jesse.forward(25)
    jesse.end_fill()



   #program for creating H

    jesse.color("navy")
    jesse.begin_fill()
    jesse.penup()
    jesse.left(90)
    jesse.left(90)
    jesse.forward(100)
    jesse.pendown()
    jesse.left(90)
    jesse.forward(50)
    jesse.right(90)
    jesse.forward(25)
    jesse.right(90)
    jesse.forward(20)
    jesse.left(90)
    jesse.forward(25)
    jesse.left(90)
    jesse.forward(20)
    jesse.right(90)
    jesse.forward(25)
    jesse.right(90)
    jesse.forward(50)
    jesse.right(90)
    jesse.forward(25)
    jesse.right(90)
    jesse.forward(20)
    jesse.left(90)
    jesse.forward(25)
    jesse.left(90)
    jesse.forward(20)
    jesse.right(90)
    jesse.forward(25)
    jesse.end_fill()

    play.mainloop()
main()
